name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Nix is required
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09-small
    # Install elinter and run lint and byte-compile
    - uses: akirak/elinter@v4
    - name: 'Lint and test with the latest release of Emacs'
      run: elinter --ert-runner -e latest
